### ISSUE TITLE
Document `noctua` caching behavior and 403 errors

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/wiki#25]
As documented in https://github.com/DyfanJones/noctua/issues/96, the `noctua` R package tries to delete results from the results S3 bucket after retrieving them. However, our read-only AWS accounts aren't permissioned to delete things from S3, resulting in a 403 error after every query.

This behavior can be disabled by enabling `noctua` caching: `noctua_options(cache_size = 10)`

We should document this flag in the `How-To/Connect-to-AWS-Resources.md` doc.

**Comment by Damonamajor** [comment]
closed with #26
